name: plugin-fn-xml-node CI Tests

env:
  plugin-id: plugin-fn-xml-node

on:
  push:
    paths:
      - ${{plugin-id}}/**
      - '.github/workflows/**'
  pull_request:
    paths:
      - ${{plugin-id}}/**
      - '.github/workflows/**'

jobs:
  build:
    env:
      working-directory: ./${{plugin-id}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: ${{env.working-directory}}
      env:
        CI: true
      run: |
        npm ci
        npm run build --if-present
        npm test
