name: plugin-fn-xml-node tests

on:
  push:
    paths:
      - 'plugin-fn-xml-node/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'plugin-fn-xml-node/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Extract Plugin-Folder-name
      id: extract
      uses: frabert/replace-string-action@master
      with:
        pattern: '(.*)-tests.yml'
        string: 'plugin-fn-xml-node-tests.yml'
        replace-with: '$1'
    - name: Extracted folder name
      env:
        GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
      run: |
        echo "Extracted folder name is ${{ steps.extract.outputs.replaced }}"
        echo "GITHUB_EVENT_PATH $env.GITHUB_EVENT_PATH"
        echo "GITHUB_WORKFLOW $GITHUB_WORKFLOW"
        echo "GITHUB_ACTION ${{ env.GITHUB_ACTION }}"
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: ${{env.working-directory}}
      env:
        CI: true
      run: |
        npm ci
        npm run build --if-present
        npm test
