# The name of the workflow node to appear in the actions and badge!
name: Syncplicity Connector
on:
  push:
    paths:
      # This must be aligned with the folder-name of you plugin
      - 'api-builder-plugin-fc-syncplicity/**'
  pull_request:
    paths:
      # This must be aligned with the folder-name of you plugin
      - 'api-builder-plugin-fc-syncplicity/**'
  release:
    types:
      - published

defaults:
  run:
    working-directory: api-builder-plugin-fc-syncplicity

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
#    - name: Debug
#      uses: hmarr/debug-action@v1.0.0
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test

  publish-gpr:
    if: contains(github.event.release.tag_name, 'plugin-fc-syncplicity')
    env:
      CI: true
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@Axway-API-Builder-Ext'
      - name: Publish to GitHub package repo
        env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npm install
          npm publish

  publish-npm:
    env:
      CI: true
    needs: [build, publish-gpr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish to NPM package repo
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
          npm install
          echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" > ~/.npmrc
          npm publish --access public