# The name of the workflow node to appear in the actions and badge!
name: Google Maps Tests

on:
  push:
    paths:
      # This must be aligned with the folder-name of you plugin
      - 'api-builder-plugin-fn-google-maps/**'
  pull_request:
    paths:
      # This must be aligned with the folder-name of you plugin
      - 'api-builder-plugin-fn-google-maps/**'

jobs:
  build:
    env:
      # This must be aligned with the folder-name of you plugin
      workingDirectory: 'api-builder-plugin-fn-google-maps'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: ${{env.workingDirectory}}
      env:
        CI: true
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        npm ci
        npm run build --if-present
        npm test
