# The name of the workflow node to appear in the actions and badge!
name: AWS Athena Tests

on:
  push:
    paths:
      # This must be aligned with the folder-name of you plugin
      - 'api-builder-plugin-fn-aws-athena/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      # This must be aligned with the folder-name of you plugin
      - 'api-builder-plugin-fn-aws-athena/**'
      - '.github/workflows/**'

jobs:
  build:
    env:
      # This must be aligned with the folder-name of you plugin
      workingDirectory: 'api-builder-plugin-fn-aws-athena'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
#    - name: Debug
#      uses: hmarr/debug-action@v1.0.0
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: ${{env.workingDirectory}}
      env:
        CI: true
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      run: |
        npm ci
        npm run build --if-present
        npm test
