name: XML-Node CI Tests

on: [push, pull_request]

jobs:
  build:
    env:
      working-directory: ./xml-node
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: ${{env.working-directory}}
      env:
        CI: true
      run: |
        npm ci
        npm run build --if-present
        npm test
